### PR TITLE
fix transform issue

### PR DESCRIPTION
**Pull request by thetarnav**

### CODE REVIEW

**Review by atk — APPROVED** [review]
This looks good to me.

**Comment by bryanmylee** [comment]
That makes perfect sense to me, thanks @thetarnav.

**Comment by bryanmylee** [comment]
@thetarnav Just realized this breaks SSR when importing the component from Astro. Seems like Astro is pulling from the `esm` build now where it used to pull from `source`.

**Comment by thetarnav** [comment]
To work with SolidStart you just need to put the library to `ssr.noExternal` in vite config
Astro is its own beast
https://github.com/withastro/astro/issues/4652
I'm sure there is a solution, but I don't know one unfortunately

**Comment by bryanmylee** [comment]
Adding `"type": "module"` back to `package.json` seems to fix this.

**Pull request merged**
